### ISSUE TITLE
Dialog backdrop covers everything

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-confirm-dialog-flow#105]
Updating from 14.0 to 14.1 breaks a use case of nested dialogs: opening a new dialog on-top of another and trying to focus a text-field, creates a backdrop that covers everything and blocks any interaction.

```java
public class ConfirmDialogBackdrop extends VerticalLayout {

    public ConfirmDialogBackdrop() {
        ConfirmDialog d1 = new ConfirmDialog();
        ConfirmDialog d2 = new ConfirmDialog();
        TextField tf = new TextField();
        Button b1 = new Button("Open dialog", event -> d1.open());
        Button b2 = new Button("Open dialog", event -> d2.open());
        this.add(b1);
        d1.add(b2);
        d2.add(tf);
    }

}
```

This is the result:

<img width="904" alt="Screenshot 2019-12-17 at 09 33 29" src="https://user-images.githubusercontent.com/851745/70978571-50ca7580-20b0-11ea-8cf1-340bf44d1b51.png">

**Comment by heruan** [comment]
Seems causes by this: https://github.com/vaadin/vaadin-overlay/pull/162

**Comment by tomivirkki** [comment]
Oh boy, we didn't consider implications on multiple overlays. Will revert the change.

**Comment by tomivirkki** [comment]
Fixed in https://github.com/vaadin/vaadin-overlay/pull/166

**Comment by tomivirkki** [comment]
The fix is released with https://github.com/vaadin/platform/releases/tag/14.1.3
