### ISSUE TITLE
Confirmdialog triggers confirmation without "real" user interaction

### ISSUE THREAD

**Issue by knoobie** [vaadin/vaadin-confirm-dialog-flow#120]
## Description of the bug

Confirmdialog confirms itself without any real user interaction, when it was created by a Button within a Grid triggered by keyboard. Looks like it listens on keyup event of the SPACE key. 

## Minimal reproducible example

* (1) Open the view 
* (2) Use TAB to focus the column with the delete button 
* (3) Press SPACE (hold it.. don't release it!) -> see below

## Expected behaviour

* (4) after releasing the space key -> Dialog is open + all items are still in the grid
* (5) user interacts with the Dialog to confirm the deletion

## Actual behaviour

* (4) after releasing the space key -> Dialog closed itself + item in grid is deleted
* ?

## Versions
* Vaadin / Flow version: 14.1.25
* OS version: ubuntu lts
* Browser version: 
  * Firefox 76 -> it happens always
  * Chromium -> it happens only if you are releasing the space key really fast

## Source Code to reproduce
```java

@Route(value = "bug-confirmdialog")
public class ConfirmDialogBug extends VerticalLayout {

  private final List<MyBean> items;
  private final Grid<MyBean> grid;

  @Autowired
  public ConfirmDialogBug() {
    items = new ArrayList<>();
    items.add(new MyBean("val 1"));
    items.add(new MyBean("val 2"));
    items.add(new MyBean("val 3"));

    grid = new Grid<>();
    grid.setSelectionMode(SelectionMode.NONE);
    grid.addColumn(b -> b.value).setFlexGrow(1).setHeader("Value");
    grid.addComponentColumn(this::createButton).setAutoWidth(true).setFlexGrow(0).setHeader("Delete");
    grid.setItems(items);
    add(grid);
  }

  private Button createButton(MyBean myBean) {
    Button button = new Button();
    button.setIcon(IconUtils.create(VaadinIcon.DEL));
    button.addThemeVariants(ButtonVariant.LUMO_ICON);
    button.getElement().setAttribute("title", "My Title");
    button.addClickListener(e -> {
      ConfirmDialog dialog = new ConfirmDialog("Delete me",
        "Are you sure?",
        "Yes", event -> {
        items.remove(myBean);
        grid.getDataProvider().refreshAll();
      }, "No", event -> {});
      dialog.open();
    });
    return button;
  }

  @AllArgsConstructor
  public class MyBean {

    public String value;
  }
}
```

**Comment by web-padawan** [comment]
I'm not sure, but this might be related to how `click` event on <kbd>Space</kbd> works in Firefox for a button. Here is a quote from [Elix library](https://github.com/elix/elix/blob/b47795144c35b2f3b5bd9d8963c592883e94834f/src/base/Button.js#L17) that contains some potentially relevant information.

> As of February 2019, Firefox automatically translates a Space/Enter key on a button into a click event that bubbles to its host. Chrome/Safari do not do this automatically.

> It's gross to look for a specific browser (Firefox), but it seems extremely hard to feature-detect this. Even if we try to create a button in a shadow at runtime and send a key event to it, Chrome/Safari don't seem to do their normal mapping of Space/Enter to a click for synthetic keyboard events.

**Comment by knoobie** [comment]
I'm wondering how the button in general is implemented - if you test it, for example in Github: 

* focus a button
* press space key (don't release it)
* the action behind the button isn't triggered immediately 
* release the space key -> action is triggered

Currently in my example above, the Button in Grid is already triggered on keyDown of the space. Isn't that to early? Could that solve the whole problem? That only happens inside a Grid, outside (just a normal Button) triggers as expected (after I release the key).

**Comment by knoobie** [comment]
I think it's related to the Grid Implementation:

https://github.com/vaadin/vaadin-grid/blob/90966ef4eec065f6f379e5b69aaf4c6bff09d439/src/vaadin-grid-keyboard-navigation-mixin.html#L46

**Comment by knoobie** [comment]
Any update on this?
