### ISSUE TITLE
Adding confirm-dialog dependency to a project affects the style of all dialogs

### ISSUE THREAD

**Issue by tulioag** [vaadin/vaadin-confirm-dialog-flow#136]
Adding confirm-dialog as a dependency to a project adds the following style to all vaadin-dialogs
```css
#content {
  height: auto;
  box-sizing: content-box;
}
```

Steps to reproduce:
1) Run vaadin-dialog-flow project (`mvn jetty:run`) and navigate to /vaadin-dialog-view
2) Verify the style is not present.
![dialog-without-confirm-dialog](https://user-images.githubusercontent.com/28783969/88672339-03a38d00-d0f0-11ea-91e2-75c5e54e6636.png)
3) Add the following dependency in the pom
```xml
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-confirm-dialog-flow</artifactId>
            <version>4.0.0.alpha1</version>
        </dependency>
```
4) Run the project again. Verify that the style is now added.
![dialog-with-confirm-dialog-in-project](https://user-images.githubusercontent.com/28783969/88672512-38174900-d0f0-11ea-9855-e4d69308a7cb.png)

**Comment by DiegoCardoso** [comment]
This should have been fixed by this (https://github.com/vaadin/vaadin-confirm-dialog/pull/107). Maybe it's still unreleased?

**Comment by DiegoCardoso** [comment]
The mentioned [PR](https://github.com/vaadin/vaadin-confirm-dialog/pull/107) is part of [`vaadin-confirm-dialog@1.3.0`](https://github.com/vaadin/vaadin-confirm-dialog/releases/tag/v1.3.0), which is part of [`vaadin-confirm-dialog-flow@4.0.0`](https://github.com/vaadin/vaadin-confirm-dialog-flow/releases/tag/v4.0.0).

Tested with the stable version and could check that the style is only applied to `vaadin-confirm-dialog`.
