### ISSUE TITLE
Setting width has no effect

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-confirm-dialog-flow#40]
Setting width has no effect on the dialog has no effect, i.e.

```java
var dialog1 = new ConfirmDialog();
dialog1.open();

var dialog2 = new ConfirmDialog();
dialog2.setWidth("500px");
dialog2.open();

var dialog3 = new ConfirmDialog();
dialog3.setWidth("1000px");
dialog3.open();
```

the three dialogs have always the same width.

**Comment by heruan** [comment]
Any progress on this?

Also, even without setting any width, the dialog does not adapt to the width of its content but the content overflows outside the dialog.

I think first of all if the dialog content has a fixed width, the dialog itself should adapt to its content's width (if not width is set on the dialog itself).

**Comment by Braus** [comment]
Bug is still active it seems.

**Comment by heruan** [comment]
I'm using this workaround at the moment:

```html
<dom-module id="vaadin-dialog-overlay-width-theme" theme-for="vaadin-dialog-overlay">
  <template>
    <style>
      [part="content"] {
        width: var(--vaadin-dialog-content-width, 512px);
      }
    </style>
  </template>
</dom-module>
```

This sets a default width of 512px which you can override setting the variable.

**Comment by heruan** [comment]
The huge problem here is that the width cannot be set based on any element attribute, since it is applied to the `vaadin-dialog-overlay` which cannot be referenced from Flow.

@alvarezguille do you think it would be possibile to teleport the `theme` attribute to the overlay?

**Comment by heruan** [comment]
Any update on this? My expectation is the same behaviour of `vaadin-dialog`: if a `(max-|min-)width` is set, respect that; if no width is set, adapt to content.

**Comment by alvarezguille** [comment]
This is on top of our maintenance backlog, we did some research but didn't conclude, sorry we haven't answered yet
