### ISSUE TITLE
Use case examples for Java developers in vaadin.com

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-confirm-dialog-flow#7]
Use cases demos:
1. "Meeting starting" "Your next meeting starts in 5 minutes" "OK"
2. "Confirm delete" “Are you sure you want to delete the item?” “Delete” (should use error style), “Cancel”
3. "Publish" “Are you sure you want to publish the article?” “Publish” (should use primary style), “Cancel”
4. "Unsaved changes" ""Do you want to save or discard your changes before navigating away?"" "Save" (primary style), "Discard" (error style), "Cancel"

**Comment by enver-haase** [comment]
Sorry, but where are those demos? The source code for Java is not there.
In fact, I cannot seem to use this at all. It does not even extend com.vaadin.flow.component.dialog.Dialog so that there is no open() --- no idea how am I supposed to use this.

**Comment by alvarezguille** [comment]
The demos are in https://vaadin.com/components/vaadin-confirm-dialog/java-examples
And the demo sources are in https://github.com/vaadin/vaadin-confirm-dialog-flow/blob/master/vaadin-confirm-dialog-flow-demo/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogView.java

**Comment by enver-haase** [comment]
I see. Thanks. I honestly did not spot that there is an open() implementation and that is how you open the dialog. I was on the wrong track when I expected the Dialog.open() to be there.
