### ISSUE TITLE
Unusable from Java? Does not derive from Dialog?

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-confirm-dialog-flow#70]
It is related to #7 .
I do not get how I am supposed to use this. Easier to write my own -- because it does not derive from com.vaadin.flow.component.dialog.Dialog I don't aven have an open() method.

**Comment by enver-haase** [comment]
```
Dialog dialog = new Dialog();

    ConfirmDialog confirmDialog = new ConfirmDialog();
    confirmDialog.setHeader(getTranslation(DIALOG_LEAVE_HEADER));
    confirmDialog.setText(getTranslation(DIALOG_LEAVE_TEXT));

    Button stayButton = new CancelButton();
    confirmDialog.setCancelButton(stayButton);

    Button leaveButton = new AcceptButton();
    confirmDialog.setConfirmButton(leaveButton);

    dialog.add(confirmDialog);
    dialog.open();
```

**Comment by enver-haase** [comment]
above code was tested as a work-around to the ConfirmDialog not extending Dialog. Does NOT work either.

**Comment by heruan** [comment]
Why do you say there is no `open()` method? There is at [ConfirmDialog.java#L489](https://github.com/vaadin/vaadin-confirm-dialog-flow/blob/9c42370a196694afeef48ab73a5ec1bc0d627ac5/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java#L489) and you should just:

```java
ConfirmDialog confirmDialog = new ConfirmDialog();
confirmDialog.setHeader(getTranslation(DIALOG_LEAVE_HEADER));
confirmDialog.setText(getTranslation(DIALOG_LEAVE_TEXT));

confirmDialog.open();
```

**Comment by alvarezguille** [comment]
Thanks @heruan for answering here.
`ConfirmDialog` doesn't extend `Dialog` but can be used in similar way with `open()` method, when opening it will self attach to body if it wasn't attached before.
[Demos](https://vaadin.com/components/vaadin-confirm-dialog/java-examples) and [demo sources](https://github.com/vaadin/vaadin-confirm-dialog-flow/blob/master/vaadin-confirm-dialog-flow-demo/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogView.java)
I'll close this issue as `ConfirmDialog` is usable from Java.
Adding `ConfirmDialog` do `Dialog` might have unexpected results and is not how it should be used.
@enver-haase if you still have issues using your custom `AcceptButton` and `CancelButton` mentioned in the snippet please create a new issue with the sources for those buttons that can be used to reproduce it.

**Comment by enver-haase** [comment]
Thanks. I stand corrected. My mistake.
